apiVersion: apps/v1
kind: Deployment
metadata:
  name: streaming-speech-demo-deployment
  labels:
    app: streaming-speech-demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: streaming-speech-demo
  template:
    metadata:
      labels:
        app: streaming-speech-demo
    spec:
      containers:
      - name: streaming-speech-demo
        image: gcr.io/streaming-speech-demo/streaming-speech-demo:latest
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: streaming-speech-demo-service
spec:
  type: NodePort
  selector:
    app: streaming-speech-demo
  ports:
  - protocol: TCP
    port: 60000
    targetPort: 3000
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: streaming-speech-demo-ingress
spec:
  tls:
  - secretName: tls-certificate
  rules:
  - http:
      paths:
      - path: /*
        backend:
          serviceName: streaming-speech-demo-service
          servicePort: 60000